---
#-------------------------------
# General Site Settings

title: Ido's Homepage
logo:
author: Ido Jeon
description: Welcome to my Homepage
email: ido.j.r2@gmail.com
phone: +49 175 5474 4134
address: Mester utca 83, 1095 Budapest
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Blog, link: "/blog" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Ido <br> Web Developer

social:
  - { icon: "ti-facebook", link: "https://www.instagram.com/diakin.j?igsh=MXVqOG5lcGlpdmxyag%3D%3D&utm_source=qr" }
  - { icon: "ti-instagram", link: "#" }
  # - { icon: "ti-dribbble", link: "#" }
  - { icon: "ti-twitter", link: "https://x.com/d452022?s=21&t=pcskYDLHMXDhzEtN_NJJhg" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Intro

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: ""

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: ""

  - title: "Review & Feedback"
    icon: "assets/images/icons/print.png"
    content: ""

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Front-End, color: "#fdb157", value: "90%" }
  - { name: Back-End, color: "#9473e6", value: "50%" }
  - { name: CI/CD, color: "#bdecf6", value: "40%" }
  - { name: ETC., color: "#ffbcaa", value: "60%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Junior Java Developer,
      icon: "icon-1.png",
      date: "Jul 2019 - Sep 2020",
      organization: "GANASYS",
    }
  - {
      name: Full-Stack Web Developer,
      icon: "icon-2.png",
      date: "Oct 2020 - Sep 2021",
      organization: "OPENTONE",
    }
  - {
      name: Front-End Web Developer,
      icon: "icon-3.png",
      date: "Oct 2021 - Sep 2023",
      organization: "RAKUTEN",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Bachelor's degree in Computer Science,
      date: "Mar 2015 - Aug 2018",
      organization: "Korea National Open University",
    }
  - {
      name: Game Contents Design Course Certificate,
      date: "Apr 2015 - Feb 2016",
      organization: "Kyungil Vocation Institution",
    }
  - {
      name: Expert in Big Data Ecosystem on Cloud Computing Course Certificate,
      date: "Jul 2014 - Jan 2015",
      organization: "Ssangyong Education Center",
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/portfolio-1.png"
    url: "/2023/10/01/rakuten-card-apply-pages/"

  - image: "assets/images/portfolio/portfolio-2.png"
    url: "/2021/09/28/vue-and-charts/"

  - image: "assets/images/portfolio/portfolio-3.png"
    url: "/2020/09/15/java-olingo-odata-api/"

  - image: "assets/images/portfolio/portfolio-4.png"
    url: "/2024/02/02/persona-in-website/"

  # - image: "assets/images/portfolio/item-5.png"
  #   url: "#"

# Portfolio Page
portfolio-label:
  - { title: "Vue & Nuxt", type: "vuejs" }
  - { title: "Java", type: "java" }
  - { title: "REST-APIs", type: "restapi" }
  - { title: "Django", type: "django" }
  # - { title: "BRANDING", type: "branding" }
  # - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/portfolio-1.png"
    url: "/2023/10/01/rakuten-card-apply-pages/"
    portfolio-type:
      - type: "vuejs"

  - image: "assets/images/portfolio/portfolio-2.png"
    url: "/2021/09/28/vue-and-charts/"
    portfolio-type:
      - type: "vuejs"
      - type: "java"
      - type: "restapi"

  - image: "assets/images/portfolio/portfolio-3.png"
    url: "/2020/09/15/java-olingo-odata-api/"
    portfolio-type:
      - type: "java"
      - type: "restapi"

  # - image: "assets/images/portfolio/item-6.png"
  #   url: "#"
  #   portfolio-type:
  #     - type: "vuejs"
  #     - type: "branding"

  # - image: "assets/images/portfolio/item-8.png"
  #   url: "#"
  #   portfolio-type:
  #     - type: "restapi"

  # - image: "assets/images/portfolio/item-5.png"
  #   url: "#"
  #   portfolio-type:
  #     - type: "design"

  - image: "assets/images/portfolio/portfolio-4.png"
    url: "/2024/02/02/persona-in-website/"
    portfolio-type:
      - type: "django"
      - type: "vuejs"
      - type: "restapi"

  # - image: "assets/images/portfolio/item-3.png"
  #   url: "#"
  #   portfolio-type:
  #     - type: "design"
  #     - type: "illustration"
  #     - type: "branding"

  # - image: "assets/images/portfolio/item-7.png"
  #   url: "#"
  #   portfolio-type:
  #     - type: "illustration"

#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------


contact-title: Contact
contact-email: ido.j.r2@gmail.com
